### ISSUE TITLE
不如我们来搞一手国外的workingTime吧！

### ISSUE THREAD

**Issue by ramen-curator** [Robin970822/WorkingTime#3]
国内不行的话，要不要试一试国外的？

在国外运营的话，就不会触碰到国内了，甚至会传播得更广，因为国外禁东西挺难的。
那这个项目就一定能推动起来了！

**Comment by 710073113** [comment]
这个总表一般多少时间更新呢

**Comment by wft44maqb** [comment]
备份: https://gitlab.com/mirror_/WorkingTime

**Comment by wft44maqb** [comment]
秃头才能变强 ZhangNanBei https://github.com/ZhangNanBei
